<form id="form1" method="post" action="<?php echo BASE_URL;?>post/nuevo">
    <input type="hidden" name="guardar" value="1" />
    <p>Titulo: <br />
        <input type="texto" name="titulo" value="<?php if(isset($this->datos['titulo'])){ echo $this->datos['titulo'];}?>"/>
    <p>Cuerpo: <br />
        <textarea name="cuerpo"  ><?php if(isset($this->datos['cuerpo'])){ echo $this->datos['cuerpo'];}?></textarea>
        
        <input type="submit" class="button" value="Guardar" />
    </p>
</form>